# Generated by Django 2.2.13 on 2020-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0025_confirm_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ManyToManyField('User', blank=True, help_text='The supervisor(s) directly above this user who should be notified when the user requests a reservation.'),
        ),
    ]