# Generated by Django 2.2.13 on 2020-10-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0025_1_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='alternate_email_address',
            field=models.EmailField(verbose_name='email address', blank=True, null=True, help_text="An alternate email address where all invitations will be sent."),
        ),
    ]
